version: '3.8'
services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: elevatorDB
    ports:
      - 127.0.0.1:3306:3306
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 10
